config/routes.rb
Rails.application.routes.draw do
  resources :college_employees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/college_employee.rb
class CollegeEmployee < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/college_employees_controller.rb
class CollegeEmployeesController < ApplicationController
  before_action :set_college_employee, only: [:show, :edit, :update, :destroy]

  # GET /college_employees
  # GET /college_employees.json
  def index
    @college_employees = CollegeEmployee.all
  end

  # GET /college_employees/1
  # GET /college_employees/1.json
  def show
  end

  # GET /college_employees/new
  def new
    @college_employee = CollegeEmployee.new
  end

  # GET /college_employees/1/edit
  def edit
  end

  # POST /college_employees
  # POST /college_employees.json
  def create
    @college_employee = CollegeEmployee.new(college_employee_params)

    respond_to do |format|
      if @college_employee.save
        format.html { redirect_to @college_employee, notice: 'College employee was successfully created.' }
        format.json { render :show, status: :created, location: @college_employee }
      else
        format.html { render :new }
        format.json { render json: @college_employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /college_employees/1
  # PATCH/PUT /college_employees/1.json
  def update
    respond_to do |format|
      if @college_employee.update(college_employee_params)
        format.html { redirect_to @college_employee, notice: 'College employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @college_employee }
      else
        format.html { render :edit }
        format.json { render json: @college_employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /college_employees/1
  # DELETE /college_employees/1.json
  def destroy
    @college_employee.destroy
    respond_to do |format|
      format.html { redirect_to college_employees_url, notice: 'College employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_college_employee
      @college_employee = CollegeEmployee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def college_employee_params
      params.require(:college_employee).permit(:name, :company, :location, :phone_no)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/college_employees_helper.rb
module CollegeEmployeesHelper
end

app/views/college_employees/_form.html.erb
<%= form_for(college_employee) do |f| %>
  <% if college_employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(college_employee.errors.count, "error") %> prohibited this college_employee from being saved:</h2>

      <ul>
      <% college_employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :company %>
    <%= f.text_area :company %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_area :location %>
  </div>

  <div class="field">
    <%= f.label :phone_no %>
    <%= f.text_field :phone_no %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/college_employees/edit.html.erb
<h1>Editing College Employee</h1>

<%= render 'form', college_employee: @college_employee %>

<%= link_to 'Show', @college_employee %> |
<%= link_to 'Back', college_employees_path %>

app/views/college_employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>College Employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Company</th>
      <th>Location</th>
      <th>Phone no</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @college_employees.each do |college_employee| %>
      <tr>
        <td><%= college_employee.name %></td>
        <td><%= college_employee.company %></td>
        <td><%= college_employee.location %></td>
        <td><%= college_employee.phone_no %></td>
        <td><%= link_to 'Show', college_employee %></td>
        <td><%= link_to 'Edit', edit_college_employee_path(college_employee) %></td>
        <td><%= link_to 'Destroy', college_employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New College Employee', new_college_employee_path %>

app/views/college_employees/new.html.erb
<h1>New College Employee</h1>

<%= render 'form', college_employee: @college_employee %>

<%= link_to 'Back', college_employees_path %>

app/views/college_employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @college_employee.name %>
</p>

<p>
  <strong>Company:</strong>
  <%= @college_employee.company %>
</p>

<p>
  <strong>Location:</strong>
  <%= @college_employee.location %>
</p>

<p>
  <strong>Phone no:</strong>
  <%= @college_employee.phone_no %>
</p>

<%= link_to 'Edit', edit_college_employee_path(@college_employee) %> |
<%= link_to 'Back', college_employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Employee</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>